name: Test Action
on:
  push:
    branches:
    - *

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: echo README.md
      run: |
        echo ./README.md
